#!/usr/bin/env bash
# Make a `clever ssh` session look like the boot environment.
#
# The stock ~/.bashrc sources ~/applicationrc (so the app's environment is
# available) but it stops part-way through in non-interactive shells, which
# is exactly how `clever ssh < script.sh` runs. Hooking ~/.bash_profile as
# well covers both cases; the rc below is written to be idempotent so being
# sourced twice is harmless.
set -uo pipefail
. "$(dirname "$0")/lib.sh"

RC="$HOME/.vm-agent-rc"
MARKER="# >>> vm-agent >>>"

cat > "$RC" <<'RCEOF'
# Generated by vm-agent - rewritten on every deploy, do not edit.

# Application + add-on environment (GH_TOKEN, CELLAR_*, APP_HOME, ...).
[ -f "$HOME/applicationrc" ] && . "$HOME/applicationrc"

# Prepend without duplicating: this file may be sourced more than once.
for d in "$HOME/.local/bin" "$HOME/.opencode/bin"; do
  case ":$PATH:" in
    *":$d:"*) ;;
    *) PATH="$d:$PATH" ;;
  esac
done
export PATH
unset d

export npm_config_prefix="$HOME/.local"
export EDITOR="${EDITOR:-vim}"
export PERSIST_ROOT="${APP_HOME:-$HOME}/persistent"

alias vm-status='curl -s localhost:8080/status | jq .'
alias vm-log='tail -n 100 -f /tmp/vm-agent-boot.log'

# Interactive sessions start in the persistent workspace, not the app
# checkout, so a stray `git init` does not land on ephemeral disk.
if [ -n "${PS1:-}" ] && [ "$PWD" = "$HOME" ] && [ -d "$HOME/workspace" ]; then
  cd "$HOME/workspace" || true
fi
RCEOF

hook() {
  local file="$1"
  grep -qF "$MARKER" "$file" 2>/dev/null && return 0
  {
    echo ""
    echo "$MARKER"
    echo '[ -f "$HOME/.vm-agent-rc" ] && . "$HOME/.vm-agent-rc"'
    echo "# <<< vm-agent <<<"
  } >> "$file"
}

hook "$HOME/.bashrc"
hook "$HOME/.bash_profile"
hook "$HOME/.zshrc"
hook "$HOME/.zprofile"

log "shell profile wired into .bashrc / .bash_profile / .zshrc / .zprofile"
