#!/usr/bin/env bash
# Make an interactive `clever ssh` session look like the boot environment.
#
# SSH sessions do not inherit the application's environment: the platform
# only writes it to ~/applicationrc. Without this, an agent started by hand
# would find no GH_TOKEN, no Cellar credentials and none of the CLIs.
set -uo pipefail
. "$(dirname "$0")/lib.sh"

RC="$HOME/.vm-agent-rc"
MARKER="# >>> vm-agent >>>"

cat > "$RC" <<'RCEOF'
# Generated by vm-agent - do not edit, it is rewritten on every deploy.

# Application + add-on environment (GH_TOKEN, CELLAR_*, ...).
[ -f "$HOME/applicationrc" ] && . "$HOME/applicationrc"

export PATH="$HOME/.local/bin:$HOME/.opencode/bin:$PATH"
export npm_config_prefix="$HOME/.local"
export EDITOR="${EDITOR:-vim}"
export PERSIST_ROOT="${PERSIST_ROOT:-/home/bas/persistent}"

# Land in the persistent workspace rather than the app checkout.
if [ -n "${PS1:-}" ] && [ "$PWD" = "$HOME" ] && [ -d "$HOME/workspace" ]; then
  cd "$HOME/workspace" || true
fi

alias vm-status='curl -s localhost:8080/status | jq .'
alias vm-log='tail -n 100 -f /tmp/vm-agent-boot.log'
RCEOF

# Idempotent hook into .bashrc.
if ! grep -qF "$MARKER" "$HOME/.bashrc" 2>/dev/null; then
  {
    echo ""
    echo "$MARKER"
    echo '[ -f "$HOME/.vm-agent-rc" ] && . "$HOME/.vm-agent-rc"'
    echo "# <<< vm-agent <<<"
  } >> "$HOME/.bashrc"
fi

# zsh is installed too and some people prefer it.
if ! grep -qF "$MARKER" "$HOME/.zshrc" 2>/dev/null; then
  {
    echo "$MARKER"
    echo '[ -f "$HOME/.vm-agent-rc" ] && . "$HOME/.vm-agent-rc"'
    echo "# <<< vm-agent <<<"
  } >> "$HOME/.zshrc"
fi

log "shell profile wired into .bashrc / .zshrc"
